
development:
  adapter: :postgresql
  enconding: unicode
  database: score_board_7_wonders
  pool: 5
  username: postgres
  password: alinedb

test:
  adapter: postgresql
  enconding: unicode
  database: score_board_7_wonders_test
  pool: 5
  username: postgres
  password: alinedb

production:
  adapter: postgres
  enconding: unicode
  database: score_board_7_wonders_prod  
  pool: 5

